### ISSUE TITLE
mvn site does not generate docs

### ISSUE THREAD

**Issue by jhlch** [OryxProject/oryx#184]
`mvn site` and `mvn site:site` (prereqs for `mvn site:stage`) both fail when run from the master branch. I get an error related to not being able to locate kafka-util jars:

[ERROR] Failed to execute goal on project kafka-util: Could not resolve dependencies for project com.cloudera.oryx:kafka-util:jar:2.0.0-SNAPSHOT: Could not find artifact com.cloudera.oryx:oryx-common:jar:tests:2.0.0-SNAPSHOT -> [Help 1]

**Comment by srowen** [comment]
Hm, works for me *but* `site` requires that the artifacts already be available locally or in Maven Central. That is, you get errors without an `install` beforehand to make the SNAPSHOT artifacts available. That sounds consistent with the error above.

With that though I do get the site built without errors and it includes javadoc -- this is how http://oryxproject.github.io/oryx/apidocs/ was generated for example.

I think that's just how `site` works because its config is not inherited, but, I have never gotten the reporting config in Maven quite right. If anyone sees a better config, by all means. But you can definitely get javadoc out of the site build.

**Comment by jhlch** [comment]
Ah, I was cutting off the maven cycle too early by running `mvn package`. Running `mvn install` first fixes everything. I figured it had to be something simple I was missing. In retrospect, the error message should have made that obvious. Thanks!
