### ISSUE TITLE
Anti-"flooding" parameter to ALS `/recommend`?

### ISSUE THREAD

**Issue by srowen** [OryxProject/oryx#220]
Sometimes, it's desirable to have more diverse recommendations even if it means demoting "good" recommendations that are very similar to other top recommendations. Investigate a simple and principled way to support a "diversity" parameter to recommendation endpoints.

**Comment by ChuyuHsu** [comment]
What do you mean by that "diversity"?

**Comment by srowen** [comment]
Just dis-similarity between items. Normally you only rank recommendations by the quality of the recommendation. But you might also want to consider how similar items are to the ones that come before it, and demote recommendations that are similar. It's tricky since there must be a tradeoff between the two, which probably has to be a request param. It's also not easy to implement efficiently in real-time.

**Comment by neerajBaji** [comment]
Yes, this indeed is very useful practically. Any pointers to relevant literature?

**Comment by srowen** [comment]
I have never come across a formal treatment of the idea. Usually people seem to mean just applying business logic, like taking 1 item from each of N categories. I have in mind something subtler but that requires some approximation or heuristic.

You can imagine weighting a candidate item's score by average dissimilarity to the current top N items. This makes the result depend a little on the order in which items are encountered.

It's also wildly inefficient. Really, you'd have to construct a set of, say, 3N candidate results first, and then try to start re-ranking from recommendation 2 downwards. 

I imagine the similarity metric would be cosine similarity.

It's not that hard, but it's pretty made-up. I'd be interested to see someone create a good clean implementation of this and explore it and tune it.

**Comment by neerajBaji** [comment]
Is this issue closed because the feature was added?

And yes, generating 3N candidates would be very inefficient; unless a part of it is offloaded to the Batch layer somehow.

Another mechanism (probably equally inefficient in terms of space complexity) could be to cache serving layer results periodically; whereby the diversity of recos is maintained on average but still does not result in heavy computation on every request. A dynamic threshold based on request load could be learned on the fly. Your thoughts?
