### ISSUE TITLE
Introduce new config variable to define fetch.message.max.bytes for OryxUpdate topic in Speed and Service layers

### ISSUE THREAD

**Issue by dsdinter** [OryxProject/oryx#224]
Added config variable for fetch.message.max.bytes in Kafka Consumer for Speed and Service layers. 
This is to support bigger messages in OryxUpdate topic beyond the default 1MB, i.e. when big feature vectors.

**Comment by srowen** [comment]
Yeah I'm OK with something like that. There's an interesting meta-question here, which is, to what extent is the app config just going to wrap a bunch of framework-specific config? at some point does it make sense to allow arbitrary pass-through configuration?

As a start it's possible to just make this size very large, since this app expects very large messages. I wonder if that's good enough to start? rather than introduce more config options.

Maybe I'm overly paranoid about blowing up the config complexity; the hope was that the Oryx config was just the essentials and abstracted away a lot of the Kafka / Spark config. At the same time, no real reason to make these settings inaccessible.

**Comment by dsdinter** [comment]
Sure, I actually started and fixed my issue with that approach but I was not sure we wanted to be able to parametrise it.
Sounds good to just add bigger size (I.e. 50MB) - I can actually do a pull request as I tested the code already.
Let me know if that is ok please.

Thanks.

**Comment by srowen** [comment]
Continued in https://github.com/OryxProject/oryx/pull/225
