### ISSUE TITLE
Oryx 1 project link is broken in oryx/src/site/markdown/index.md

### ISSUE THREAD

**Issue by HyukjinKwon** [OryxProject/oryx#335]
The link in main site:

![2017-07-03 11 49 09](https://user-images.githubusercontent.com/6477701/27776454-a9642aa8-5fe5-11e7-8a9f-81b2814666b2.png)

is broken as below:

![2017-07-03 11 49 13](https://user-images.githubusercontent.com/6477701/27776456-adffb9ce-5fe5-11e7-95e0-1a3b396cd82e.png)

This is trivial but I can't fix it because I don't know if it is simply decided to be removed out or just a broken link.

**Comment by srowen** [comment]
Hm, the link works OK for me right now. The project is still there: https://github.com/cloudera/oryx

**Comment by srowen** [comment]
Oh, wait, it's been made private. That's why I can see it, because I'm part of the Cloudera org. 
Yeah, they are cleaning out a lot of old projects from the corporate github that are defunct. I will see if I can transfer ownership of it just so it's available somewhere, or else make the source available in the new repo.

I'll update the docs in any event.
